# Generated by Django 3.0.8 on 2020-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=15)),
                ('grade', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('like', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('area', models.CharField(max_length=15)),
            ],
        ),
    ]
