# Generated by Django 3.0.8 on 2020-08-11 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='grade_users',
            field=models.ManyToManyField(related_name='grade_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
