# Generated by Django 3.0.8 on 2020-08-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_description',
            field=models.TextField(blank=True),
        ),
    ]
