# Generated by Django 3.0.8 on 2020-08-11 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybook', '0002_auto_20200812_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='grade_users',
            field=models.ManyToManyField(related_name='User_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='userDetail',
        ),
        migrations.AddField(
            model_name='usersubscribe',
            name='user_books',
            field=models.ManyToManyField(related_name='book_posts', to='pybook.Book'),
        ),
    ]
